game:
  stallness_factor: 100
  screen: 
    width: 800
    height: 600
  bluebox:
    width: 50
    height: 50
  redbox:
    width: 500
    height: 500
  title: "Move the blue box to the red box"
  fps: 60
  background_color: [0, 0, 0]